// <auto-generated />
using Airsoft.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Airsoft.Server.Migrations
{
    [DbContext(typeof(ClubDb))]
    [Migration("20260906113209_SteamSessions")]
    partial class SteamSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Airsoft.Server.ClubRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("Credits")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Defense")
                        .HasColumnType("bytea");

                    b.Property<long>("Money")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Clubs", null, t =>
                        {
                            t.HasCheckConstraint("club_nonnegative", "\"Money\" >= 0 AND \"Credits\" >= 0 AND \"Rating\" >= 0 AND \"Version\" >= 0");
                        });
                });

            modelBuilder.Entity("Airsoft.Server.LedgerRow", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .HasColumnType("text");

                    b.Property<long>("Credits")
                        .HasColumnType("bigint");

                    b.Property<long>("Money")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Owner", "Operation");

                    b.ToTable("Ledger");
                });

            modelBuilder.Entity("Airsoft.Server.MatchRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("AcceptedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Attacker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Defender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Economy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Fence")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Input")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("LeaseUntil")
                        .HasColumnType("bigint");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Result")
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Attacker");

                    b.HasIndex("Defender");

                    b.HasIndex("Status", "LeaseUntil");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Airsoft.Server.OperationRow", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Owner", "Key");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Airsoft.Server.PolicyRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Airsoft.Server.SessionRow", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Until")
                        .HasColumnType("bigint");

                    b.HasKey("TokenHash");

                    b.HasIndex("Owner");

                    b.HasIndex("TicketHash")
                        .IsUnique();

                    b.ToTable("SessionRow");
                });

            modelBuilder.Entity("Airsoft.Server.LedgerRow", b =>
                {
                    b.HasOne("Airsoft.Server.ClubRow", null)
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Airsoft.Server.MatchRow", b =>
                {
                    b.HasOne("Airsoft.Server.ClubRow", null)
                        .WithMany()
                        .HasForeignKey("Attacker")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airsoft.Server.ClubRow", null)
                        .WithMany()
                        .HasForeignKey("Defender")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Airsoft.Server.OperationRow", b =>
                {
                    b.HasOne("Airsoft.Server.ClubRow", null)
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Airsoft.Server.SessionRow", b =>
                {
                    b.HasOne("Airsoft.Server.ClubRow", null)
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
